# Generated by Django 5.0.6 on 2024-07-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
