# Generated by Django 5.0.6 on 2024-07-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hall_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
