# Generated by Django 5.0.6 on 2024-07-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_district_region_remove_hall_location_hall_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='google_map',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
