# Generated by Django 5.0.6 on 2024-07-23 13:02

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_account_application_account_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Ariza', 'verbose_name_plural': 'Arizalar'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'Zal', 'verbose_name_plural': 'Zallar'},
        ),
        migrations.AlterModelOptions(
            name='hallimage',
            options={'verbose_name': 'Rasm', 'verbose_name_plural': 'Rasmlar'},
        ),
        migrations.AddField(
            model_name='application',
            name='director',
            field=models.CharField(default='', max_length=200, verbose_name='Rahbar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='director',
            field=models.CharField(default='', max_length=200, verbose_name="Ma'sul odam"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='account_number',
            field=models.CharField(max_length=200, verbose_name='Hisob raqam'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.CharField(blank=True, max_length=6, unique=True, verbose_name='Ariza ID'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_from',
            field=models.DateField(verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_to',
            field=models.DateField(verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Elektron pochta'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='app.hall', verbose_name='Zal'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tashkilot nomi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=200, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('review', 'Kurib chiqilmoqda'), ('accept', 'Tasdiqlandi'), ('reject', 'Bekor qilindi')], default='review', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Mavjudligi'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='capacity',
            field=models.IntegerField(verbose_name="Sig'imi"),
        ),
        migrations.AlterField(
            model_name='hall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.district', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='google_map',
            field=models.URLField(blank=True, null=True, verbose_name='Google map havolasi'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='image',
            field=models.ImageField(upload_to=app.models.upload_path_hall, verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Zal nomi'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='price',
            field=models.BigIntegerField(verbose_name="Narxi/so'm"),
        ),
        migrations.AlterField(
            model_name='hall',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.region', verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='size',
            field=models.CharField(max_length=200, verbose_name='Hajmi/m2'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='hall',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AlterField(
            model_name='hallimage',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.hall', verbose_name='Zal'),
        ),
        migrations.AlterField(
            model_name='hallimage',
            name='image',
            field=models.ImageField(upload_to=app.models.upload_path_hall_image, verbose_name='Rasm'),
        ),
    ]
