# Generated by Django 5.0.6 on 2024-07-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_application_options_alter_hall_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='inn',
            field=models.CharField(default='', max_length=200, verbose_name='INN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='phone_number',
            field=models.CharField(default='', max_length=200, verbose_name='Telefon raqam'),
            preserve_default=False,
        ),
    ]
