# Generated by Django 5.0.6 on 2024-07-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_hall_inn_hall_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='inn',
            field=models.BigIntegerField(verbose_name='INN'),
        ),
    ]
