# Generated by Django 5.0.6 on 2024-07-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_hall_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Manzil'),
            preserve_default=False,
        ),
    ]
