# Generated by Django 5.0.6 on 2024-07-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_application_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='inn',
            field=models.CharField(default='', max_length=200, verbose_name='INN'),
            preserve_default=False,
        ),
    ]
