# Generated by Django 5.0.7 on 2024-08-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_application_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='google_map',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Google map havolasi'),
        ),
    ]
